### ISSUE TITLE
Google API error - [400] Invalid values[3][0]: struct_value { fields { key: "_state" value {string_value: "ticket_title"}}

### ISSUE THREAD

**Issue by cverdes** [lowdefy/lowdefy#1432]
#### Describe the bug

Using lowdefy version 4.0.0-alpha.37 and following the tutorial included in the documentation, after completing Step 5.20 I get the following error after press the Submit button:
```
Google API error - [400] Invalid values[3][0]: struct_value { fields { key: "_state" value {string_value: "ticket_title"}}
```
and the following log is displayed on the server console:
```
20:13:43 ∙ {
20:13:43 ∙   route: 'request',
20:13:43 ∙   params: {
20:13:43 ∙     blockId: undefined,
20:13:43 ∙     pageId: 'new-ticket',
20:13:43 ∙     payload: {},
20:13:43 ∙     requestId: 'save_data'
20:13:43 ∙   }
20:13:43 ∙ } Started request
20:13:43 ∙ { authorized: true } Authorize Request
20:13:45 ∙ {
20:13:45 ∙   params: { id: 'save_data', type: 'GoogleSheetAppendOne' },
20:13:45 ∙   err: RequestError: Google API error - [400] Invalid values[3][0]: struct_value {
20:13:45 ∙     fields {
20:13:45 ∙       key: "_state"
20:13:45 ∙       value {
20:13:45 ∙         string_value: "ticket_title"
20:13:45 ∙       }
20:13:45 ∙     }
20:13:45 ∙   }
20:13:45 ∙   
20:13:45 ∙       at callRequestResolver (file:///home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/node_modules/.pnpm/@lowdefy+api@4.0.0-alpha.37/node_modules/@lowdefy/api/dist/routes/request/callRequestResolver.js:28:21)
20:13:45 ∙       at processTicksAndRejections (node:internal/process/task_queues:96:5)
20:13:45 ∙       at async callRequest (file:///home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/node_modules/.pnpm/@lowdefy+api@4.0.0-alpha.37/node_modules/@lowdefy/api/dist/routes/request/callRequest.js:79:22)
20:13:45 ∙       at async handler (/home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/.next/server/pages/api/request/[pageId]/[requestId].js:223:26)
20:13:45 ∙       at async Object.apiResolver (/home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:9)
20:13:45 ∙       at async NextNodeServer.runApi (/home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:481:9)
20:13:45 ∙       at async Object.fn (/home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:735:37)
20:13:45 ∙       at async Router.execute (/home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36)
20:13:45 ∙       at async NextNodeServer.run (/home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:347:29)
20:13:45 ∙       at async NextNodeServer.handleRequest (/home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:285:20)
20:13:45 ∙ } Google API error - [400] Invalid values[3][0]: struct_value {
20:13:45 ∙   fields {
20:13:45 ∙     key: "_state"
20:13:45 ∙     value {
20:13:45 ∙       string_value: "ticket_title"
20:13:45 ∙     }
20:13:45 ∙   }
20:13:45 ∙ }
```
It's only happens with version 4.0.0-alpha.37. ***With version 3.23.3 it works as expected and a new row is added in the Google Sheet.***

#### To Reproduce

1. Create a folder
2. Change directory to the new folder
3. Execute `npx lowdefy@alpha init`
4. Extract the files from the attached zip file into the new folder
5. Execute `npx lowdefy@alpha dev`
6. Complete the form with some data
7. Press the `Submit` button

#### Screenshots

Error with version 4.0.0-alpha.37:
![Screenshot from 2022-12-14 20-14-01](https://user-images.githubusercontent.com/6440942/207738823-20e56093-5b01-4c63-b3a0-907cf1e14857.png)

Row added with the same code but with the version 3.23.3:
![image](https://user-images.githubusercontent.com/6440942/207741112-5bf080a0-9421-480a-a5e9-fa5374878346.png)

#### Lowdefy Version

Version 4.0.0-alpha.37

[lowdefy-files.zip](https://github.com/lowdefy/lowdefy/files/10232481/lowdefy-files.zip)

**Comment by cverdes** [comment]
Perhaps it's related to this issue, that executing the `npx lowdefy@alpha dev` the warning `⚠ Operator type "_state" was used but is not defined` is shown:

```
21:34:59 ⚠ 
---------------------------------------------------
  You are using an experimental version of Lowdefy.
  Features may change at any time.
---------------------------------------------------
21:34:59 ∙ Running 'lowdefy dev'. Lowdefy app version 4.0.0-alpha.37.
21:34:59 ℹ Starting development server.
21:35:00 ∙ Dependencies install successfully.
21:35:00 ∙ > @lowdefy/server-dev@4.0.0-alpha.37 start /home/cverdes/Documents/dev/lowdefy-alpha/.lowdefy/dev
21:35:00 ∙ > node manager/run.mjs
21:35:00 ⚠ Operator type "_state" was used but is not defined.
21:35:00 ∙ Built config.
21:35:01 ∙ Installed plugins.
21:35:19 ∙ Built app.
21:35:19 ∙ ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

**Comment by Gervwyk** [comment]
Thanks @cverdes, Google connection has been removed from tutorial.
