### ISSUE TITLE
Error on installing starter-jwt plugin.

### ISSUE THREAD

**Issue by kemeris2000** [lowdefy/lowdefy#1608]
#### Describe the bug

After setting up [starter-jwt](https://github.com/lowdefy/starter-jwt) plugin, the following error occur when loading home page.

```
15:50:36 ✖ https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
15:50:36 ✖     at assertConfig (/var/www/lowdefy/node_modules/.pnpm/next-auth@4.20.1_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/core/lib/assert.js:42:12)
15:50:36 ✖     at AuthHandler (/var/www/lowdefy/node_modules/.pnpm/next-auth@4.20.1_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/core/index.js:70:52)
15:50:36 ✖     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
15:50:36 ✖     at async NextAuthHandler (/var/www/lowdefy/node_modules/.pnpm/next-auth@4.20.1_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/next/index.js:24:19)
15:50:36 ✖     at async auth (/var/www/lowdefy/app/.lowdefy/dev/.next/server/chunks/97.js:261:16)
15:50:36 ✖     at async Object.apiResolver (/var/www/lowdefy/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:9)
15:50:36 ✖     at async NextNodeServer.runApi (/var/www/lowdefy/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:481:9)
15:50:36 ✖     at async Object.fn (/var/www/lowdefy/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:735:37)
15:50:36 ✖     at async Router.execute (/var/www/lowdefy/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36)
15:50:36 ✖     at async NextNodeServer.run (/var/www/lowdefy/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:347:29) {
15:50:36 ✖   code: 'NO_SECRET'
15:50:36 ✖ }
```

I could be related to next-auth parameter, but I am not sure where to place it.
https://next-auth.js.org/configuration/options#nextauth_secret

#### To Reproduce

[starter-jwt](https://github.com/lowdefy/starter-jwt) example

#### Lowdefy Version

4.0.0-rc.9

**Comment by kemeris2000** [comment]
NEXTAUTH_SECRET variable was missing in my project .env file

after that I have got warning because of wrong "ttps" protocol schema 
```
12:06:31 ✖ [next-auth][warn][NEXTAUTH_URL]
12:07:43 ∙ {ttps://next-auth.js.org/warnings#nextauth_url
```
fixed this with NEXTAUTH_URL environment variable

**Comment by Gervwyk** [comment]
Hi @kemeris2000 
You'd need to set it in your `.env` to include `NEXTAUTH_SECRET` and `NEXTAUTH_URL`.
We'll add it to the docs, thanks.

**Comment by kemeris2000** [comment]
Thank you, I already have managed to install this plugin. After fixing some errors it works.

**Comment by miicchelle** [comment]
It would be great if the docs would be updated for this. Having the same issue.
