### ISSUE TITLE
Node 16 Required?

### ISSUE THREAD

**Issue by zanderson-aim** [lowdefy/lowdefy#789]
#### Describe the bug

Upgrading to 3.20.4 seems to cause a node error when you deploy using the official container. 

#### To Reproduce

Deploy code inside container and do a FROM  lowdefy/lowdefy:3.20.4. I was able to fix this by rebuilding lowdefy/lowdefy FROM node:16-alpine instead of node:14-alpine and it seems to work. It looks like the function replaceAll was added in node 15+.

Dockerfile that produces the error

```
FROM node:14-buster AS build

# Set working directory and node user
WORKDIR /home/node/lowdefy

RUN chown node:node /home/node/lowdefy

USER node

# Copy app config, and change ownership of files to "node" user
COPY  --chown=node:node  . .

# Build the Lowdefy config using the Lowdefy CLI
RUN npx lowdefy@3.20.4 build

# Use the correct Lowdefy base image
FROM lowdefy/lowdefy:3.20.4

# Copy build output from build stage
COPY --from=build --chown=node:node /home/node/lowdefy/.lowdefy/build ./build

# Copy contents of public directory into image
COPY --chown=node:node ./public ./public

# Run the server on start
CMD ["node", "./dist/server.js"]
```

#### Screenshots

When you try access the application you get this in the logs

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: indexHtml.replaceAll is not a function
    at /home/node/lowdefy/node_modules/@lowdefy/server/dist/index.js:70:31
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/node/lowdefy/node_modules/@lowdefy/server/dist/index.js:22:103)
    at _next (/home/node/lowdefy/node_modules/@lowdefy/server/dist/index.js:24:194)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Lowdefy Version

3.20.4

**Comment by Gervwyk** [comment]
Hi @zanderson-aim 

Thanks for bringing this to our attention. We'll implement a fix in the next release.
